services:
  - type: web
    name: lungguide-ai
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile

    envVars:
      - key: GEMINI_API_KEY
        sync: false

      - key: GEMINI_CHAT_MODEL
        value: gemini-2.5-flash

      - key: GEMINI_EMBEDDING_MODEL
        value: gemini-embedding-001

      - key: RETRIEVAL_TOP_K
        value: "5"

      - key: MIN_RELEVANCE_SCORE
        value: "0.28"

      - key: CHUNK_SIZE
        value: "800"

      - key: CHUNK_OVERLAP
        value: "120"

      - key: BACKEND_HOST
        value: "0.0.0.0"

      - key: CORS_ORIGINS
        value: "*"